name: zokeworksV2
favicon: null
layout_spectrum: 0.5697433829773217
typography_spectrum: 0.30170076666399837
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f192c'
    - '#2d715e'
    - '#d17672'
    - '#8fb091'
    - '#fdfefe'
  brandStrength: 0.7496448184829205
  lightness: 0.980212883092463
  saturation: 0.3808283372782171
  rhythmicContrast: 0.33886606339365244
purpose: []
