name: zokeworksV2
favicon: null
layout_spectrum: 0.9113
typography_spectrum: 0.30170076666399837
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2b2320'
    - '#c5c438'
    - '#826441'
    - '#f72e52'
  brandStrength: 0
  lightness: 0.980212883092463
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
